### ISSUE TITLE
how to compute CMC and rank-m

### ISSUE THREAD

**Issue by Phoebe-star** [zhunzhong07/person-re-ranking#1]
how to compute CMC and rank-m
can you teach me 
thanks

**Comment by zhunzhong07** [comment]
Please see the details in evaluation/utils/evaluation.m @Phoebe-star

**Comment by Phoebe-star** [comment]
how to call your code to run  evaluation.m ?
thanks thanks

**Comment by zhunzhong07** [comment]
@Phoebe-star please see the example for details.

**Comment by Phoebe-star** [comment]
The  distance matrix  between each pair of gallery and probe person   ,

if  the distance value  is large ,it can express  the   gallery and probe person are the same?
or   the distance value  is small ,it can express  the   gallery and probe person are the same?
