### ISSUE TITLE
How to generate the results picture

### ISSUE THREAD

**Issue by YHangbin** [zhunzhong07/person-re-ranking#12]
Hi, @zhunzhong07. Thanks for the great code. I found a good picture in your paper.  I want to draw a picture like that to show the result. But I don't know how it was generated. Do you use the drawing software or generate it through code? Thank you for your help.
![2018-06-21 19-39-14](https://user-images.githubusercontent.com/23275340/41716981-d3265ee0-758a-11e8-869a-f4eabc32f0c9.png)

**Comment by zhunzhong07** [comment]
Hi, I generate the results by code. Given the re-ID results, I save the top-N images for each query image.

Bests,
Zhun

**Comment by YHangbin** [comment]
@zhunzhong07 Thank you very much, I am very sorry, missed your answer.

**Comment by rmxhhh** [comment]
Hi, can you share your code?  I am  learning your work recently. Thank you very much. @zhunzhong07
