### ISSUE TITLE
Request GPU version of re_rank function

### ISSUE THREAD

**Issue by jpainam** [zhunzhong07/person-re-ranking#14]
Hi!
When using multi query evaluation in Market1501, this 
```python
 original_dist = np.concatenate(
      [np.concatenate([q_q_dist, q_g_dist], axis=1),
       np.concatenate([q_g_dist.T, g_g_dist], axis=1)],
      axis=0)
```
shows MemoryError even in a  32GB memory window PC. This line of code should run on the GPU
Kindly provide a re_rank_gpu version of this function for very large evaluation
Thank you

**Comment by PayneYong** [comment]
Hi!
Have you solved it out?
I met the Memory Error too.
![2018-11-09 16-01-59](https://user-images.githubusercontent.com/7524271/48324749-37652780-e66d-11e8-902c-4a95bcf6d690.png)

**Comment by jpainam** [comment]
No, i didn't solve. I decided not to include re-ranking at all since the author of the implementation rarely replies

**Comment by PayneYong** [comment]
OK
