### ISSUE TITLE
Do the junk images also participate in re-ranking?

### ISSUE THREAD

**Issue by rocketbear** [zhunzhong07/person-re-ranking#15]
For the Market-1501 dataset, there are a number of junk images for each query image in the gallery set, and some of the junk images are from from the same camera as the query image, so they may affect the retrieval performance if they are used for re-ranking.

I want to know:
1. Do the junk images participate in the re-ranking process?
2. If 1 is true, is it a widely accepted procedure in other published papers?

**Comment by zhunzhong07** [comment]
Hi, sorry for the late reply. We have two versions of re-ranking method, i.e. Matlab and Python. For the original Matlab version, we use all the images (including junk images) for re-ranking. While in the python version, we discard the junk images from the gallery. These two versions achieve almost the same results. So you can either ignore or apply the junk images in the re-ranking process. However, we may not sure which image is junk image in the practice, so I advise to use all the images (including junk images) in the re-ranking process.
