### ISSUE TITLE
Does your re-ranking works with VIPeR.v1.0 datasets settings where we have one image per identity in the gallery?

### ISSUE THREAD

**Issue by jpainam** [zhunzhong07/person-re-ranking#17]
Hi!
I want to know if re-ranking can be applied to VIPeR.v1.0 dataset where we have one image per identity in the gallery? i tried and got less results compared with no-reranking.
Thank you

**Comment by zhunzhong07** [comment]
Our approach assumes that there are multi positive samples in the gallery. So our approach may fail to improve the performance in a small dataset.

**Comment by jpainam** [comment]
Thank you
