### ISSUE TITLE
query not an issue

### ISSUE THREAD

**Issue by shashankvkt** [zhunzhong07/person-re-ranking#2]
hello sir,
My doubt is that under the file re_ranking.m what does  "backward_k_neigh_index" variable signify?
does it signify the k reciprocal NN? if not could you kindly enlighten me as to what does it mean.

Thank you

**Comment by zhunzhong07** [comment]
@shashankvkt the backward_k_neigh_index means the knn of each k-nearest neighbors of query I.
For example, given a query I, the knn (forward_k_neigh_index ) of I is [A,B,C,D], then the backward_k_neigh_index  is the knn of [A,B,C,D].

**Comment by shashankvkt** [comment]
Thank you very much sir
