### ISSUE TITLE
Issue about mAP

### ISSUE THREAD

**Issue by ericxian1997** [zhunzhong07/person-re-ranking#20]
It seems that values of rank1 and mAP produced by state-of-the-art methods on CUHK03 are very close (some method's mAP are even higher than rank-1 accuracy).  But on other datasets such as Market-1501 and DukeMTMC-reID, mAP is usually 10％~15％ lower than rank-1 accuracy. 
What is the reason for higher mAP on CUHK03?
I use the evaluation code to test my model trained on CUHK03, the mAP is also 10％~15％ lower than rank-1 accuracy, which is inconsistent with the values reported.

**Comment by zhunzhong07** [comment]
In the CUHK03 new protocol, there have few ground truth images for each identity so that the mAP will be close to the rank-1 accuracy. Did you use the new setting in the evaluation of your model?

**Comment by ericxian1997** [comment]
I use the new setting in the evaluation of my model and use your evaluation code for CUHK03, but the mAP is still 15％ lower than mAP. (I trained a ResNet-50 based model and got ~51％ Rank1, ~34％mAP on CUHK03)
