### ISSUE TITLE
about k and k1 k2

### ISSUE THREAD

**Issue by nm46nm** [zhunzhong07/person-re-ranking#24]
不扯英文了……
关于k k1 k2，有个疑问：
按你论文所述，R是由马氏距离的前k个邻居生成的，然后再做k/2的扩充，得到R*，然后论文定义说R*的大小为k1，而N(p,k)的大小为k2。而N(p,k)不正是马氏距离前k个邻居嘛，也就是应该有k=k2。

但是在代码中，为什么R*的生成是用k1个邻居以及k1/2个扩充，后来做Local Query Expansion的时候用的又是k2。是不是搞混了。

**Comment by zhunzhong07** [comment]
Sorry for the confusion. The k used for K-reciprocal Nearest Neighbors is denoted as k1. While the k used for local query expansion is denoted as k2.
