### ISSUE TITLE
what does these data mean?

### ISSUE THREAD

**Issue by wu-han** [zhunzhong07/person-re-ranking#3]
label_train = importdata('data/Market-1501/train_label.mat');
cam_train =  importdata('data/Market-1501/train_cam.mat');
train_feature = importdata(['feat/Market-1501/' netname '_IDE_train.mat']);

Hello sir, I understand what the data 'feat/Market-1501/' netname '_IDE_train.mat' means. 
But I cannot see the creation process of  'data/Market-1501/train_label.mat' and 'data/Market-1501/train_cam.mat'. What does the these data mean? How can I create it ? Could you give me a little explanation, sir ?
Thank you very much !

**Comment by zhunzhong07** [comment]
@wu-han You can obtain it from the Market-1501 dataset, it contains the groundtruth of ID and Cam for each image.
