### ISSUE TITLE
What is correct: 1,360 identities in 13,164 images or 1,467 identities in 14,096 images?

### ISSUE THREAD

**Issue by MLenthousiast** [zhunzhong07/person-re-ranking#4]
The claim is made in this repo and the according paper that there are 1,467 identities in 14,096 images for the CUHK03 dataset. However, the original authors claim that there are  1,360 identities in 13,164 images, see also their [website](http://www.ee.cuhk.edu.hk/~xgwang/CUHK_identification.html).

So which is correct and how can there be a difference in these numbers in the first place?

**Comment by zhunzhong07** [comment]
In the original paper, they only use part of the data set for training and testing. In our new protocol, we use all available images, and splits the CUHK03 dataset into training set and testing set similar to that of Market-1501, which consist of 767 identities and 700 identities respectively. In this way, you only need to train and test once, and there are more query and gallery in the testing set.
