### ISSUE TITLE
rank-m  problem

### ISSUE THREAD

**Issue by Phoebe-star** [zhunzhong07/person-re-ranking#5]
I  use your cuhk03   rank 
IDE_ResNet_50 + XQDA + re-ranking   |  rank-1  is  38.1%

I  use  the code   [cmc](https://github.com/Cysu/open-reid/blob/master/reid/evaluation_metrics/ranking.py)  the rank-1  is  also  38.1%

but  I use  the  code  [cmc](https://github.com/Cysu/Person-Reid/blob/master/reid/utils/cmc.py)  the rank-1 is 63%

**Comment by zhunzhong07** [comment]
In our code, we use a new protocol splits for CUHK03 dataset, this protocokl split the dataset into training set and testing set similar to that of Market-1501, which consist of 767 identities and 700 identities respectively.

Our new protocol is different from the one in open-reid.

**Comment by Phoebe-star** [comment]
I know you  have new protocol  , but  I use your   IDE features (  fixed features ) to compute CMC .
I use the  two  cmc  code , they  have  different value

**Comment by zhunzhong07** [comment]
In open re-id, you should use the same testing protocol as the new protocol, and use the 'Market-1501' metric in the ope re-id.

**Comment by Phoebe-star** [comment]
1.you say the  testing protocol of  open re-id,  is  used  by  everyone   ( old )
and your protocol  is the new  
so use cmc method   is  not  match
so  open re-id  cmc  method   's  protocal  is the same as  your , because  rank-1  are 38.1%
     Person-Reid  cmc method  's protocal is not the same as your  , because rank-1  are  63%  and 38.1%


2. do you know  how  to  choose  cuhk03  dataset for training   and  cmc ( validation cmc ) ?  (general)

**Comment by zhunzhong07** [comment]
The open re-id is the general way to split CUHK03 dataset, which have 1000+ identities for training, and 100 identities for testing,  and needs to training/testing 20 runs.
