### ISSUE TITLE
k values question

### ISSUE THREAD

**Issue by pengjiao123** [zhunzhong07/person-re-ranking#7]
In your paper，you  set k1 to 20, k2 to 6 in experiments on Market-1501 . I want to know why the values of k1，k2 are these.（you  set k1 to 7, k2 to 3 in experiments on CUHK-03 is on this question.）

**Comment by zhunzhong07** [comment]
we use train/val to select the best parameters. In CUHK-03, there are fewer ground-truth under gallery for each ID, so we use smaller k1 and k2 for this dataset.
