### ISSUE TITLE
Python Version Re-Ranking that Accepts Distance Matrices as Input

### ISSUE THREAD

**Issue by huanghoujing** [zhunzhong07/person-re-ranking#8]
Hi, Zhun Zhong. I modify the python version to
- accept distance matrices instead of raw features, so that
  - distance is not restricted to Euclidean Distance
  - distance can be computed beforehand, independent of the re-ranking logic
- handle the difference of `/` division between python 2 and 3
- replace `numpy.float16` with `numpy.float32` for numerical precision

It can be found [here](https://github.com/huanghoujing/AlignedReID-Re-Production-Pytorch/blob/9cf2861/aligned_reid/utils/re_ranking.py).

Thanks a lot for your re-ranking work. Thanks also to @michuanhaohao.

**Comment by zhunzhong07** [comment]
Great! I have added your modified version to our code. Thanks for your interest in our work.
