### ISSUE TITLE
Where does 'cuhk03_multishot_config_detected.mat' come from?

### ISSUE THREAD

**Issue by handong1587** [zhunzhong07/person-re-ranking#9]
I can see in person-re-ranking/evaluation/data/CUHK03/save_img.m, you load 2 files like:
`cuhk03_multishot_config_detected.mat`
`cuhk03_multishot_config_labeled.mat`
I wonder where does these 2 files come from because I cannot find any other relevant code to create or describe them.
Thanks!

**Comment by zhunzhong07** [comment]
You can ignore save_img.m and *_config*.mat . It is a config file (contain image name list) for CUHK03, we have generated images with PNG format, it is available in [Baiduyun](https://pan.baidu.com/s/1o8txURK) or [GoogleDriver](https://drive.google.com/file/d/0B7TOZKXmIjU3OUhfd3BPaVRHZVE/view).

**Comment by handong1587** [comment]
Thanks for your kind reply. :-)
